// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include "member-pskel.hxx"

#include "member_type-pskel.hxx"

// member_pskel
//

void member_pskel::
type_parser (::member_type_pskel& p)
{
  this->type_parser_ = &p;
}

void member_pskel::
ref_parser (::xml_schema::long_pskel& p)
{
  this->ref_parser_ = &p;
}

void member_pskel::
role_parser (::xml_schema::string_pskel& p)
{
  this->role_parser_ = &p;
}

void member_pskel::
parsers (::member_type_pskel& type,
         ::xml_schema::long_pskel& ref,
         ::xml_schema::string_pskel& role)
{
  this->type_parser_ = &type;
  this->ref_parser_ = &ref;
  this->role_parser_ = &role;
}

member_pskel::
member_pskel ()
: type_parser_ (0),
  ref_parser_ (0),
  role_parser_ (0),
  v_state_attr_stack_ (sizeof (v_state_attr_), &v_state_attr_first_)
{
}

// member_pskel
//

void member_pskel::
type (const osm::ObjectType&)
{
}

void member_pskel::
ref (long long)
{
}

void member_pskel::
role (const ::std::string&)
{
}

#include <cassert>

// Attribute validation and dispatch functions for member_pskel.
//
bool member_pskel::
_attribute_impl_phase_one (const ::xml_schema::ro_string& ns,
                           const ::xml_schema::ro_string& n,
                           const ::xml_schema::ro_string& s)
{
  if (n == "type" && ns.empty ())
  {
    if (this->type_parser_)
    {
      this->type_parser_->pre ();
      this->type_parser_->_pre_impl ();
      this->type_parser_->_characters (s);
      this->type_parser_->_post_impl ();
      const osm::ObjectType& tmp (this->type_parser_->post_member_type ());
      this->type (tmp);
    }

    static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ())->type = true;
    return true;
  }

  if (n == "ref" && ns.empty ())
  {
    if (this->ref_parser_)
    {
      this->ref_parser_->pre ();
      this->ref_parser_->_pre_impl ();
      this->ref_parser_->_characters (s);
      this->ref_parser_->_post_impl ();
      long long tmp (this->ref_parser_->post_long ());
      this->ref (tmp);
    }

    static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ())->ref = true;
    return true;
  }

  if (n == "role" && ns.empty ())
  {
    if (this->role_parser_)
    {
      this->role_parser_->pre ();
      this->role_parser_->_pre_impl ();
      this->role_parser_->_characters (s);
      this->role_parser_->_post_impl ();
      const ::std::string& tmp (this->role_parser_->post_string ());
      this->role (tmp);
    }

    return true;
  }

  return false;
}

void member_pskel::
_pre_a_validate ()
{
  this->v_state_attr_stack_.push ();
  v_state_attr_& as = *static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ());

  as.type = false;
  as.ref = false;
}

void member_pskel::
_post_a_validate ()
{
  v_state_attr_& as = *static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ());

  if (!as.type)
    this->_expected_attribute (
      "", "type");
  if (!as.ref)
    this->_expected_attribute (
      "", "ref");

  this->v_state_attr_stack_.pop ();
}

// Begin epilogue.
//
//
// End epilogue.

