// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef BOUND_PIMPL_HXX
#define BOUND_PIMPL_HXX

#include "bound-pskel.hxx"

class bound_pimpl: public virtual bound_pskel
{
  public:
  virtual void
  pre ();

  virtual void
  post_bound ();
};

#endif // BOUND_PIMPL_HXX
