// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "bound-pimpl.hxx"

// bound_pimpl
//

void bound_pimpl::
pre ()
{
}

void bound_pimpl::
post_bound ()
{
}

