// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef MEMBER_TYPE_PIMPL_HXX
#define MEMBER_TYPE_PIMPL_HXX

#include "member_type-pskel.hxx"
#include "../elements/osmelements.h"

class member_type_pimpl: public virtual member_type_pskel,
  public ::xml_schema::string_pimpl
{
  public:
  virtual void
  pre ();

  virtual osm::ObjectType
  post_member_type ();
};

#endif // MEMBER_TYPE_PIMPL_HXX
