// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "member-pimpl.hxx"

// member_pimpl
//

void member_pimpl::
pre ()
{
}

void member_pimpl::
type (const osm::ObjectType& type)
{
	tp=type;
}

void member_pimpl::
ref (long long ref)
{
	id=ref;
}

void member_pimpl::
role (const ::std::string& role)
{
	rl=role;
}

std::pair<std::string, std::shared_ptr<osm::Element> > member_pimpl::
post_member ()
{
	std::shared_ptr<osm::Element> ptr;
	switch(tp)
	{
	case osm::ObjectType::Node:
		ptr = std::shared_ptr<osm::Element>(new osm::Node(id));
		break;
	case osm::ObjectType::Way:
		ptr = std::shared_ptr<osm::Element>(new osm::Way(id));
		break;
	case osm::ObjectType::Relation:
		ptr = std::shared_ptr<osm::Element>(new osm::Relation(id));
		break;
	}
	return std::pair<std::string, std::shared_ptr<osm::Element> >(rl, ptr);
}

