// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "member_type-pimpl.hxx"

// member_type_pimpl
//

void member_type_pimpl::
pre ()
{
}

osm::ObjectType member_type_pimpl::
post_member_type ()
{
  const ::std::string& v (post_string ());

  if(v=="node")
	  return osm::ObjectType::Node;
  if(v=="way")
	  return osm::ObjectType::Way;
  if(v=="relation")
	  return osm::ObjectType::Relation;
  return osm::ObjectType::Node;
}

