// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "nd-pimpl.hxx"

// nd_pimpl
//

void nd_pimpl::
pre ()
{
}

void nd_pimpl::
ref (long long ref)
{
  id=ref;
}

int64_t nd_pimpl::
post_nd ()
{
  return id;
}

