// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef ND_PIMPL_HXX
#define ND_PIMPL_HXX

#include "nd-pskel.hxx"

class nd_pimpl: public virtual nd_pskel
{
  public:
  virtual void
  pre ();

  virtual void
  ref (long long);

  virtual int64_t
  post_nd ();
  private:
  int64_t id;
};

#endif // ND_PIMPL_HXX
