// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include "nd-pskel.hxx"

// nd_pskel
//

void nd_pskel::
ref_parser (::xml_schema::long_pskel& p)
{
  this->ref_parser_ = &p;
}

void nd_pskel::
parsers (::xml_schema::long_pskel& ref)
{
  this->ref_parser_ = &ref;
}

nd_pskel::
nd_pskel ()
: ref_parser_ (0),
  v_state_attr_stack_ (sizeof (v_state_attr_), &v_state_attr_first_)
{
}

// nd_pskel
//

void nd_pskel::
ref (long long)
{
}

#include <cassert>

// Attribute validation and dispatch functions for nd_pskel.
//
bool nd_pskel::
_attribute_impl_phase_one (const ::xml_schema::ro_string& ns,
                           const ::xml_schema::ro_string& n,
                           const ::xml_schema::ro_string& s)
{
  if (n == "ref" && ns.empty ())
  {
    if (this->ref_parser_)
    {
      this->ref_parser_->pre ();
      this->ref_parser_->_pre_impl ();
      this->ref_parser_->_characters (s);
      this->ref_parser_->_post_impl ();
      long long tmp (this->ref_parser_->post_long ());
      this->ref (tmp);
    }

    static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ())->ref = true;
    return true;
  }

  return false;
}

void nd_pskel::
_pre_a_validate ()
{
  this->v_state_attr_stack_.push ();
  v_state_attr_& as = *static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ());

  as.ref = false;
}

void nd_pskel::
_post_a_validate ()
{
  v_state_attr_& as = *static_cast< v_state_attr_* > (this->v_state_attr_stack_.top ());

  if (!as.ref)
    this->_expected_attribute (
      "", "ref");

  this->v_state_attr_stack_.pop ();
}

// Begin epilogue.
//
//
// End epilogue.

