// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "node-pimpl.hxx"

// node_pimpl
//

void node_pimpl::
pre ()
{
	tags.clear();
}

void node_pimpl::
tag (const std::pair<std::string, std::string>& tag)
{
	tags.insert(tag);
}

void node_pimpl::
id (long long id)
{
	_id=id;
}

void node_pimpl::
lat (double lat)
{
  lt=lat;
}

void node_pimpl::
lon (double lon)
{
  ln=lon;
}

osm::Node node_pimpl::
post_node ()
{
  osm::Node ret(_id, lt, ln);
  ret.tags=tags;
  return ret;
}

