// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef OSM_XML_PIMPL_HXX
#define OSM_XML_PIMPL_HXX

#include "osm_xml-pskel.hxx"

#include "member_type-pimpl.hxx"

#include "member-pimpl.hxx"

#include "nd-pimpl.hxx"

#include "node-pimpl.hxx"

#include "osm-pimpl.hxx"

#include "relation-pimpl.hxx"

#include "tag-pimpl.hxx"

#include "way-pimpl.hxx"

#include "bound-pimpl.hxx"

#endif // OSM_XML_PIMPL_HXX
