// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef RELATION_PIMPL_HXX
#define RELATION_PIMPL_HXX

#include "relation-pskel.hxx"
#include "../elements/osmelements.h"
#include <map>

class relation_pimpl: public virtual relation_pskel
{
public:
	virtual void
	pre ();

	virtual void
	tag (const std::pair<std::string, std::string>&);

	virtual void
	member (const std::pair<std::string, std::shared_ptr<osm::Element> >&);

	virtual void
	id (long long);

	virtual osm::Relation
	post_relation ();
private:
	std::set<osm::Tag> tags;
	std::multimap<std::string, std::shared_ptr<osm::Element> > members;
	int64_t _id;
};

#endif // RELATION_PIMPL_HXX
