// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "tag-pimpl.hxx"

// tag_pimpl
//

void tag_pimpl::
pre ()
{
}

void tag_pimpl::
k (const ::std::string& k)
{
	key=k;
}

void tag_pimpl::
v (const ::std::string& v)
{
	value=v;
}

std::pair<std::string, std::string> tag_pimpl::
post_tag ()
{
  return std::pair<std::string, std::string>(key, value);
}

