// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef TAG_PIMPL_HXX
#define TAG_PIMPL_HXX

#include "tag-pskel.hxx"

class tag_pimpl: public virtual tag_pskel
{
public:
	virtual void
	pre ();

	virtual void
	k (const ::std::string&);

	virtual void
	v (const ::std::string&);

	virtual std::pair<std::string, std::string>
	post_tag ();
private:
	std::string key,value;
};

#endif // TAG_PIMPL_HXX
