// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef WAY_PIMPL_HXX
#define WAY_PIMPL_HXX

#include "way-pskel.hxx"
#include "../elements/osmelements.h"

class way_pimpl: public virtual way_pskel
{
public:
	virtual void
	pre ();

	virtual void
	tag (const std::pair<std::string, std::string>&);

	virtual void
	nd (int64_t);

	virtual void
	id (long long);

	virtual osm::Way
	post_way ();
private:
	std::vector<osm::Node> nodes;
	int64_t _id;
	std::set<osm::Tag> tags;
};

#endif // WAY_PIMPL_HXX
